FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /build
COPY . .

RUN mvn -pl Services/payment-service -am clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

# crear carpeta para SQLite
RUN mkdir -p /app/data

COPY --from=build /build/Services/payment-service/target/*.jar app.jar

EXPOSE 8080

CMD ["sh", "-c", "java -Dserver.port=${PORT:-8080} -jar /app/app.jar"]
